fixed: error on Odoo version 13 & 14
fixed view error on odoo version 13 & 14 due to there is the absent of ControlPanel and SearchPanel:
```
Traceback:
TypeError: Cannot read property 'modelExtension' of undefined
    at Class.init (http://localhost:8069/web/static/src/js/views/abstract_view.js:201:72)
    at Class.prototype.<computed> [as init] (http://localhost:8069/web/static/src/js/core/class.js:90:38)
    at Class.init (http://localhost:8069/hello_world_view/static/src/js/hello_world_view.js:118:21)
    at Class.prototype.<computed> [as init] (http://localhost:8069/web/static/src/js/core/class.js:90:38)
    at new Class (http://localhost:8069/web/static/src/js/core/class.js:107:33)
    at Class._createViewController (http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:191:24)
    at http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:306:43

```